### ISSUE TITLE
openspeech install error

### ISSUE THREAD

**Issue by miziworld** [sooftware/openspeech#10]
안녕하세요, pip 으로 openspeech install시 패키지를 찾지못하는 에러가 계속 발생하여 질문드립니다.
![image](https://user-images.githubusercontent.com/17849068/121015178-a54a3f00-c7d5-11eb-863a-8a7d918773b6.png)

**Comment by sooftware** [comment]
pip install openspeech-core 되실까요?

**Comment by miziworld** [comment]
파이썬 버젼 문제였던것 같습니다. python3.7 이상을 추천하신다고 하여 python3.6.9와 python3.7.4를 같이 깔아서 진행하고 있는데 어떤 패키지는 3.7이상이 요구되고 어떤건 3.6이 지원되네요..ㅠㅠ 우선은 3.6으로 하여 설치하였습니다. 

그리고 몇가지 질문이 더 있는데
1. 혹시 manifest파일은 KoSpeech에서와 같이 transcripts.txt라고 생각하면 될까요?
2. dataset path와 maniscripts path는 /openspeech/openspeech/data/ 에 같이 넣어주면 될까요?
감사합니다.

**Comment by sooftware** [comment]
1. 네 다만, 약간 바뀐 점이 있어서 새로 생성하시는 것을 추천드립니다.  
2. dataset path는 KsponSpeech의 최상위 디렉토리를 지정해주시면 되고, manifest path는 지금 생성된게 없으시다면 원하시는 경로에 txt 파일 형식으로 지정해주시면 될 것 같습니다. Ex) `../../../manifest.txt`
  
그리고 evaluation을 위해 evaluation 데이터셋 경로도 추가적으로 설정해주셔야 합니다. (ai hub를 통해 다운 받으실 수 있습니다.  
경로 지정 관련해서는 설명보시면 아마 쉽게 사용 가능하실 것 같습니다.

**Comment by miziworld** [comment]
p{margin-top:0;margin-bottom:0}
    


    안녕하세요,

혹시  KsponSpeech data에 대한 manifest.txt 파일을 공유받을 수 있을지 여쭤봅니다.
train data로는 KsponSpeech01~05번을 사용하고 있으며 eval_data는 KsponSpeech_eval내 파일들을 사용하고 있습니다
AI hub에서 데이터셋 사용 승인 화면입니다

--------- 원본 메일 ---------

    
        보낸사람: Soohwan Kim ***@***.***>
        받는사람: sooftware/openspeech ***@***.***>
        
            참조: miziworld ***@***.***>, Author ***@***.***>
        
        날짜: 21.06.07 22:45 GMT +0900
        제목: Re: [sooftware/openspeech] openspeech install error (#10)
        
        
    
    
        

네 다만, 약간 바뀐 점이 있어서 새로 생성하시는 것을 추천드립니다.
dataset path는 KsponSpeech의 최상위 디렉토리를 지정해주시면 되고, manifest path는 지금 생성된게 없으시다면 원하시는 경로에 txt 파일 형식으로 지정해주시면 될 것 같습니다. Ex) ../../../manifest.txt

그리고 evaluation을 위해 evaluation 데이터셋 경로도 추가적으로 설정해주셔야 합니다. (ai hub를 통해 다운 받으실 수 있습니다.
경로 지정 관련해서는 설명보시면 아마 쉽게 사용 가능하실 것 같습니다.

**Comment by sooftware** [comment]
제 개인 메일로 보내주시고 다운로드 링크 눌러서 공유 신청 해주시겠어요? (sh951011@gmail.com)

**Comment by miziworld** [comment]
혹시 액세스 요청드렸는데 승인되었을까요?

나의 iPhone에서 보냄

**Comment by sooftware** [comment]
보내주신 메일에 이미지가 보이지 않아서요. 다시 보내주실래요?

**Comment by miziworld** [comment]
지금 다시 보냈는데 확인되었을까요..?ㅠㅠ
