### ISSUE TITLE
vocab keyError

### ISSUE THREAD

**Issue by miziworld** [sooftware/openspeech#20]
안녕하세요, vocab_label.csv가 생성되지않아서 이 csv파일은 KoSpeech에서 사용하던 aihub_character_labels.csv파일을 대체하여 사용하였습니다. 그런데 KeyError가 발생하게 되어 질문드립니다. 혹시 openspeech에서 ./hydra_train.py를 실행하면 자동으로 _label.csv 파일이 생성되나요?
![image](https://user-images.githubusercontent.com/17849068/121687414-4a7a5580-cafd-11eb-9c3d-fbaddb53cf47.png)

**Comment by sooftware** [comment]
네 생성됩니다.
실행한 커맨드 포함해시 이슈 남겨주세요.

김수환 드림.

2021년 6월 11일 (금) 오후 9:38, miziworld ***@***.***>님이 작성:

**Comment by miziworld** [comment]
제가 쓰던 .csv파일을 없애고 그냥 hydra_train.py만 실행시키게 되면
![image](https://user-images.githubusercontent.com/17849068/121688030-f91e9600-cafd-11eb-85e1-5517f5593bf9.png)

이렇게 나옵니다.

**Comment by hasangchun** [comment]
안녕하세요!

KoSpeech에서 사용하던 aihub_character_labels.csv 파일은 <blank> 토큰이 2000번인데 OpenSpeech에서는 3번이라 다시 생성하시는 것을 추천드립니다.

커맨드에 vocab.vocab_path=$레이블 파일이 저장되기 원하는 경로(ex. ../kspon_character_labels.csv) 한번 추가해보시겠어요?

**Comment by miziworld** [comment]
우선은 공유해주신 csv파일로 실행시켜보았는데 똑같은 커맨드를 입력하였을때
![image](https://user-images.githubusercontent.com/17849068/121851585-46328000-cd29-11eb-9f22-fb6ae230f957.png)
stage값을 train 또는 test로 설정해주어야 하는것같은데 이부분은 argument로 넣어주어야 하는건가요?

**Comment by sooftware** [comment]
@hasangchun 에러 있는거 같은데 확인하고 수정해주세요~

**Comment by sooftware** [comment]
@miziworld 현재 최신 깃 클론해서 실행한게 맞을까요?

**Comment by miziworld** [comment]
넵 현재 v0.2로 올라온 최신버전으로 사용하고 있습니다

**Comment by sooftware** [comment]
아 그리고 +로 eval_dataset 관련 파라미터도 넣어주셔야 해요. 버그 리포트해주셔서 감사합니다.

**Comment by hasangchun** [comment]
```
├── $dataset_path
    ├── KsponSpeech_01
    └── KsponSpeech_02
    └── KsponSpeech_03
    └── KsponSpeech_04
    └── KsponSpeech_05
```
그리고 학습 데이터도 이러한 구조로 되어있는지 한번 확인해주시면 좋을 것 같아요!

**Comment by sooftware** [comment]
`apply_spec_augment` 변수가 MelSpectrogramConfig에 없는 듯. @hasangchun  시간될 때 처리해줘.

**Comment by miziworld** [comment]
> ```
> ├── $dataset_path
>     ├── KsponSpeech_01
>     └── KsponSpeech_02
>     └── KsponSpeech_03
>     └── KsponSpeech_04
>     └── KsponSpeech_05
> ```
> 
> 그리고 학습 데이터도 이러한 구조로 되어있는지 한번 확인해주시면 좋을 것 같아요!

데이터셋같은 경우에는 KsponSpeech_01~05 안에있는 data들을 KsponSpeech_01안으로 합쳐서 모아놓고 그에대한 manifest 파일안의 경로도 수정해주었습니다.  그리고 eval 같은경우도 command에도 추가하고 configuration.py에도 추가해놓았습니다.

혹시 해당오류 해결되면 commnet 남겨주시면 감사하겠습니다!

**Comment by sooftware** [comment]
최신 git 에서 `pip install -e .`으로 설치해보실래요?

**Comment by sooftware** [comment]
`MelSpectrogramConfigs`에 `apply_spec_augment`가 없다는게 이해가 가질 않네요.  
분명히 있는데..

**Comment by miziworld** [comment]
python3.6과 3.7버전을 혼용해서 pip으로 install하다보니 중간에 설치되지 않은 패키지들이 있었던것 같습니다 ㅠㅠ 감사합니다.
그리고 보면 train dataset의 일부를 index를 나누어서 eval_data로 사용하고 aihub에서 받은 KsponSpeech_eval 안에 있는 파일들을 test dataset으로 사용하는 것 같은데 맞나요?  

그리고 train dataset같은경우에는 말씀주신것과 같이 _01~_05 폴더가 각각 있어야 실행이 되어서 나누어서 진행하였고 
![image](https://user-images.githubusercontent.com/17849068/122058494-a0fdd180-ce26-11eb-9b69-4a655f7a616b.png)
이러한 에러가 발생하는데 혹시나 testset이나 validset path에 오류가 있나싶어서

test.dataset_path는
----KsponSpeech_eval
     |______eval_clean
     |______eval_other
같이 구성되어있을 경우 KsponSpeech_eval로도 잡아도보고 그 하나위의 경로로도 잡아보았는데 해결되지 않아 질문드립니다.

항상 빠른 답변 감사드립니다..ㅠㅠ

**Comment by miziworld** [comment]
python3.6과 python3.7을 혼용하여 pip으로 설치하다보니 정상적으로 깔리지않은 패키지가 있었던것 같습니다.
아예 새로운 환경에서 Python3.7만을 사용하여 재설치하였더니 그 오류는 해결이 되었습니다.
또한 원래는 train dataset을 Kspon01~05를 01에 하나로 합쳐서 진행했었는데 다시 01~05로 나누어 진행하고 있습니다.

그리고 training dataset을 일부 나누어 eval dataset으로 사용하고 aihub에서 받은 eval dataset은 test dataset으로 넣어주는것 같은데 이게 맞을까요?
![image](https://user-images.githubusercontent.com/17849068/122061234-49149a00-ce29-11eb-9bf5-0e9287f58c2e.png)
이렇게 진행하였을때 위의 오류는 해결이 되는데 
![image](https://user-images.githubusercontent.com/17849068/122061341-60538780-ce29-11eb-9105-50865a168b9c.png)

또 이러한 오류가 발생하게 되네요 ㅠㅠ not valid라고 뜨는 해당 pcm파일들은 모두 존재합니다

**Comment by sooftware** [comment]
그렇다면 해당 pcm 파일을 load 해보시겠어요?  
아마 pcm 파일이 깨져있을 것 같네요

**Comment by miziworld** [comment]
해당 pcm파일을 재생시켜보았을때는 정상적으로 작동이되는데 혹시나해서 manifest에서 오류가 나는 pcm항목들을 지우고 다시 실행시켜본 결과 다른 pcm파일들에서도 똑같은 문제가 발생하네요.
_parse_adio에서 signal이 None값이 뜨는 부분이라 signal값들을 출력해보았는데 정상적으로 인수들이 들어가고있는것같긴 합니다.
혹시 개발자님께서는 KsponSpeech 데이터를 사용할 때 이런 문제가 없으셨나요? 
![image](https://user-images.githubusercontent.com/17849068/122390791-5064b080-cfad-11eb-89fb-0a166c62274d.png)

**Comment by sooftware** [comment]
이상하네요. 저희는 정상 작동하는데.. 해당 폴더에 접근권한이 없는건 아닐까요?
