### ISSUE TITLE
LR Scheduler doesn't work

### ISSUE THREAD

**Issue by sooftware** [sooftware/openspeech#34]
## Information

- Model I am using (ListenAttendSpell, Transformer, Conformer ...): All
- LR Scheduler doesn't work (all schedulers)

## To reproduce

Skip

**Comment by sooftware** [comment]
https://github.com/PyTorchLightning/pytorch-lightning/discussions/8042

**Comment by sooftware** [comment]
This is pytorch-lightning bug. https://github.com/PyTorchLightning/pytorch-lightning/issues/8057

**Comment by tchaton** [comment]
Hey @sooftware,

This was a mis-use of Pytorch Lightning.
See the correct way to setup your schedulers,
https://github.com/PyTorchLightning/pytorch-lightning/issues/8057#issuecomment-865058609

Best,
T.C

**Comment by sooftware** [comment]
@tchaton Thanks, I'll try!

**Comment by sooftware** [comment]
Fix
