### ISSUE TITLE
Training with Colab

### ISSUE THREAD

**Issue by jung-youjin** [sooftware/openspeech#44]
# ❓ Questions & Help

## Details

Hello! Thank you for great project. 

First of all I am a newbie to this field and due to lack of hardware environment, I only have access to GPUs through Google colab. 

Is training possible for Jasper model using KsponSpeech in Google colab? I am concerned as colab only gives continuous access to GPUs only for 12 hours which I can't determine whether it is an enough time for training through this project.

Thank you! 😄

**Comment by sooftware** [comment]
Hello! Thank you for your interest.  
Unfortunately, since speech recognition takes a long time, 12 hours will not be enough.  
And especially the Jasper model is a model that takes a long time to train in my experience.

**Comment by jung-youjin** [comment]
@sooftware Thank you so much for your help! May I ask for your opinions on 24 hours instead? I'm planning to get an upgraded colab.

**Comment by sooftware** [comment]
If you use KsponSpeech, it will be difficult with Colab. It will take more than a few days by multi-gpu.

**Comment by jung-youjin** [comment]
Oh, I see! Thank you so much for your help! 🙏🏼
