### ISSUE TITLE
validation checek "NoneType' object has no attribute 'transpose"

### ISSUE THREAD

**Issue by miziworld** [sooftware/openspeech#46]
안녕하세요 training시작을 했을 때 데이터 경로지정, manifest파일, vocab파일 등을 가지고 실행시켰을때 계속해서 

![image](https://user-images.githubusercontent.com/17849068/125753305-1b9459a5-8b6e-47ab-97b7-23ebdc5219ee.png)

![image](https://user-images.githubusercontent.com/17849068/125753330-4d1b333b-2d8b-4d27-a4ac-5a6c0058d5cc.png)

이러한 에러가 발생하는데 도대체 왜그런건지 해결이 안되어서 질문드립니다...
vocab같은 경우는 올려주신 sp.model과 kspon_subword_manifest.txt 사용하고 있으며 GPU는 RTX3090, Pytorch 1.8.1 버전 사용중입니다.

**Comment by miziworld** [comment]
저의 경우에는 MODEL=LISTEN_ATTEND_SPELL 그리고 criterion=joint_ctc_cross_entropy를 사용했더니 저런 에러가 발생하였습니다.
그 후 model=deepspeech2, criterion=ctc로 바꾸었더니 위의 문제가 해결되고 epoch0 이 시작되었습니다 ㅠㅠㅠㅠㅠ...
criterion을 joint_ctc_cross_entropy를 사용했을때는 model을 deepspeech2로 하였을때 지원하지않는다고 떴던것같은데 모델에 맞는 criterion이 따로 있는건지 정리해주시거나 수정해주시면 좋을것같습니다!!  감사합니다!!

**Comment by hasangchun** [comment]
안녕하세요! joint_ctc_cross_entropy를 사용하시려면 joint_ctc가 앞에 붙어있는 (ex. joint_ctc_conformer_lstm, joint_ctc_listen_attend_spell) 모델을 사용해주시면 좋을 것 같습니다. 
모델에 맞는 criterion이 따로 있어 wiki에 따로 정리해놓겠습니다. (https://github.com/sooftware/openspeech/wiki)

감사합니다.

**Comment by hasangchun** [comment]
https://github.com/sooftware/openspeech/wiki/Criterion-suitable-for-the-model
여기 참고 해주시면 좋을 것 같아요.
감사합니다.
